const entrepreneurshipQuestions = [
  // === GENERAL ENTREPRENEURSHIP QUESTIONS ===
  {q:"What is entrepreneurship?",a:["Starting and managing a new business","Working for a large corporation","Investing in the stock market","Buying real estate"],c:"Starting and managing a new business"},
  {q:"Who is an entrepreneur?",a:["A person who starts a business","A manager in a company","A government employee","An investor only"],c:"A person who starts a business"},
  {q:"What is a startup?",a:["A new business with innovative ideas","A charity organization","A small retail shop","A large corporation"],c:"A new business with innovative ideas"},
  {q:"What is venture capital?",a:["Investment in startups","Bank loans","Government grants","Personal savings"],c:"Investment in startups"},
  {q:"What is a business plan?",a:["A document describing goals and strategies","An advertisement plan","A tax report","A marketing slogan"],c:"A document describing goals and strategies"},
  {q:"What does MVP stand for?",a:["Minimum Viable Product","Most Valuable Person","Market Value Proposition","Main Venture Plan"],c:"Minimum Viable Product"},
  {q:"What is bootstrapping?",a:["Starting a business with personal funds","Using outside investors","Government funding","Borrowing from banks"],c:"Starting a business with personal funds"},
  {q:"What is a pitch deck?",a:["Presentation to attract investors","Company slogan","Business license","Financial report"],c:"Presentation to attract investors"},
  {q:"What is scalability?",a:["Ability to grow without losing efficiency","Ability to downsize quickly","Ability to reduce cost","Ability to hire more people"],c:"Ability to grow without losing efficiency"},
  {q:"What is innovation in entrepreneurship?",a:["Introducing new ideas or methods","Copying other businesses","Hiring new staff","Cutting prices"],c:"Introducing new ideas or methods"},
  {q:"What is a revenue model?",a:["Plan for generating income","Customer feedback form","Expense sheet","Production plan"],c:"Plan for generating income"},
  {q:"What is a pivot in business?",a:["Changing direction after feedback","Shutting down the company","Increasing product price","Hiring a new CEO"],c:"Changing direction after feedback"},
  {q:"What is an exit strategy?",a:["Plan to leave or sell a business","Marketing strategy","Hiring policy","Pricing strategy"],c:"Plan to leave or sell a business"},
  {q:"What is equity?",a:["Ownership share in a company","Company debt","Employee salary","Profit margin"],c:"Ownership share in a company"},
  {q:"What is a co-founder?",a:["Someone who starts a company with another","An investor","A supplier","A client"],c:"Someone who starts a company with another"},
  {q:"What is cash flow?",a:["Money moving in and out of business","Company assets","Employee benefits","Customer retention"],c:"Money moving in and out of business"},
  {q:"What is the main goal of social entrepreneurship?",a:["Creating social impact","Maximizing profits","Selling luxury goods","Building franchises"],c:"Creating social impact"},
  {q:"What is a business incubator?",a:["Organization that helps startups grow","A marketing agency","A government office","A product manufacturer"],c:"Organization that helps startups grow"},
  {q:"What is risk-taking in entrepreneurship?",a:["Making decisions with uncertain outcomes","Avoiding all changes","Following trends","Delegating tasks"],c:"Making decisions with uncertain outcomes"},
  {q:"What is market research?",a:["Studying target customers and competition","Copying competitors’ ideas","Advertising a product","Reducing prices"],c:"Studying target customers and competition"},
  {q:"What is a franchise?",a:["A business that licenses its brand and model","A type of social enterprise","A government-owned company","A startup accelerator"],c:"A business that licenses its brand and model"},
  {q:"What is a unique selling proposition (USP)?",a:["What makes a product different","A company’s price strategy","An investment plan","A hiring method"],c:"What makes a product different"},
  {q:"What is a break-even point?",a:["When revenue equals costs","When profit is highest","When expenses increase","When company expands"],c:"When revenue equals costs"},
  {q:"What is networking in business?",a:["Building professional relationships","Posting on social media","Donating to charity","Investing in ads"],c:"Building professional relationships"},
  {q:"What is customer validation?",a:["Testing if customers like your product","Sending invoices","Collecting emails","Hiring customer service"],c:"Testing if customers like your product"},
  {q:"What is intellectual property (IP)?",a:["Legal rights to inventions or ideas","Company budget","Office space","Customer database"],c:"Legal rights to inventions or ideas"},
  {q:"What is a lean startup?",a:["Building a business efficiently with minimal waste","A startup with many employees","A startup focused on physical products","A heavily funded company"],c:"Building a business efficiently with minimal waste"},
  {q:"What is business scalability?",a:["Ability to increase output without raising costs too much","Hiring more employees","Buying more equipment","Expanding office space"],c:"Ability to increase output without raising costs too much"},
  {q:"What does ROI stand for?",a:["Return on Investment","Rate of Income","Revenue on Innovation","Result of Interest"],c:"Return on Investment"},
  {q:"What does SWOT stand for?",a:["Strengths, Weaknesses, Opportunities, Threats","Sales, Work, Operations, Targets","Strategy, Wealth, Organization, Tactics","System, Workflow, Output, Trends"],c:"Strengths, Weaknesses, Opportunities, Threats"},
  {q:"What is seed funding?",a:["Initial capital to start a business","Funding after IPO","A government grant","Revenue from sales"],c:"Initial capital to start a business"},
  {q:"What is the gig economy?",a:["Work based on short-term contracts","Full-time employment","Government jobs","Factory work"],c:"Work based on short-term contracts"},
  {q:"What is an elevator pitch?",a:["A quick, persuasive business summary","A company report","A financial forecast","A hiring interview"],c:"A quick, persuasive business summary"},
  {q:"Why do most startups fail?",a:["Lack of market need","Too much marketing","Too many employees","Low prices"],c:"Lack of market need"},
  {q:"What is crowdfunding?",a:["Raising funds from many small investors","Getting a bank loan","Merging with another company","Selling assets"],c:"Raising funds from many small investors"},
  {q:"What is product-market fit?",a:["When a product meets customer needs","When a company hires staff","When a product gets media coverage","When prices are lowered"],c:"When a product meets customer needs"},
  {q:"What is a serial entrepreneur?",a:["Someone who starts multiple businesses","An investor","A manager","A consultant"],c:"Someone who starts multiple businesses"},
  {q:"What is a disruptive innovation?",a:["A product that changes an industry","A new marketing slogan","An employee bonus","A temporary trend"],c:"A product that changes an industry"},
  {q:"What is the primary purpose of a prototype?",a:["Testing a concept before launch","Final product release","Legal approval","Advertising design"],c:"Testing a concept before launch"},
  {q:"What is a micro-entrepreneur?",a:["Someone running a very small business","An investor","A tech startup founder","A franchise manager"],c:"Someone running a very small business"},

  // === ANECDOTAL QUESTIONS (FAMOUS ENTREPRENEURS) ===
  {q:"Which entrepreneur started Apple in a garage?",a:["Steve Jobs","Elon Musk","Bill Gates","Jeff Bezos"],c:"Steve Jobs"},
  {q:"Who said 'Your most unhappy customers are your greatest source of learning'?",a:["Bill Gates","Steve Jobs","Mark Zuckerberg","Larry Page"],c:"Bill Gates"},
  {q:"Which entrepreneur founded Tesla and SpaceX?",a:["Elon Musk","Richard Branson","Jeff Bezos","Larry Ellison"],c:"Elon Musk"},
  {q:"Which company did Jeff Bezos start from his garage?",a:["Amazon","Google","eBay","Netflix"],c:"Amazon"},
  {q:"Who famously dropped out of college and started Microsoft?",a:["Bill Gates","Elon Musk","Larry Page","Mark Cuban"],c:"Bill Gates"},
  {q:"Which entrepreneur founded Virgin Group?",a:["Richard Branson","Elon Musk","Steve Jobs","Jeff Bezos"],c:"Richard Branson"},
  {q:"Who created Facebook from a dorm room?",a:["Mark Zuckerberg","Elon Musk","Larry Page","Sergey Brin"],c:"Mark Zuckerberg"},
  {q:"Which entrepreneur said 'Stay hungry, stay foolish'?",a:["Steve Jobs","Jeff Bezos","Jack Ma","Elon Musk"],c:"Steve Jobs"},
  {q:"Which Chinese entrepreneur founded Alibaba?",a:["Jack Ma","Pony Ma","Lei Jun","Ren Zhengfei"],c:"Jack Ma"},
  {q:"Who founded Google along with Sergey Brin?",a:["Larry Page","Bill Gates","Elon Musk","Jeff Bezos"],c:"Larry Page"}
];
