// ===== CRITICAL LOGIC: question structure =====
let marketingQuestions = [
  {q:"What is the main goal of traditional marketing?",a:["Mass communication","SEO optimization","Influencer partnerships","Email campaigns"],c:"Mass communication"},
  {q:"Which platform is most used for digital marketing?",a:["Instagram","Radio","Newspapers","Billboards"],c:"Instagram"},
  {q:"Who is called the father of modern marketing?",a:["Philip Kotler","David Ogilvy","Edward Bernays","Peter Drucker"],c:"Philip Kotler"},
  {q:"What does SEO stand for?",a:["Search Engine Optimization","Social Engagement Output","Sales Enhancement Option","Service Engine Operation"],c:"Search Engine Optimization"},
  {q:"What type of marketing uses TV and print ads?",a:["Traditional Marketing","Content Marketing","Inbound Marketing","Affiliate Marketing"],c:"Traditional Marketing"},
  {q:"What does PPC stand for?",a:["Pay Per Click","Post Product Campaign","Public Promotion Cycle","Personal Product Click"],c:"Pay Per Click"},
  {q:"What does branding primarily create?",a:["Recognition","Immediate Sales","Discounts","Web Traffic"],c:"Recognition"},
  {q:"What is influencer marketing based on?",a:["Trust and Influence","Low Prices","Random Selection","Cold Calls"],c:"Trust and Influence"},
  {q:"Which is a form of inbound marketing?",a:["Blogging","Telemarketing","Billboards","TV Commercials"],c:"Blogging"},
  {q:"Who was known as the father of public relations?",a:["Edward Bernays","David Ogilvy","Philip Kotler","Claude Hopkins"],c:"Edward Bernays"},
  {q:"What tool is key for measuring digital campaigns?",a:["Analytics","Flyers","TV Ratings","Phone Surveys"],c:"Analytics"},
  {q:"What does ROI stand for?",a:["Return on Investment","Rate of Interest","Reach of Influence","Revenue on Idea"],c:"Return on Investment"},
  {q:"Which social media is known for short videos?",a:["TikTok","Facebook","LinkedIn","Reddit"],c:"TikTok"},
  {q:"What’s a landing page?",a:["A focused webpage for conversion","A home page","A random article","An about section"],c:"A focused webpage for conversion"},
  {q:"What marketing style did David Ogilvy pioneer?",a:["Advertising with research","Guerrilla marketing","Digital branding","Event marketing"],c:"Advertising with research"},
  {q:"What is the main purpose of email marketing?",a:["Engage customers directly","Build websites","Print coupons","Design logos"],c:"Engage customers directly"},
  {q:"What kind of marketing uses limited time offers?",a:["Promotional marketing","Organic marketing","Affiliate marketing","Guerrilla marketing"],c:"Promotional marketing"},
  {q:"What’s the main focus of content marketing?",a:["Providing value","Direct selling","Random posting","Viral ads"],c:"Providing value"},
  {q:"What does CPM mean?",a:["Cost Per Mille","Customer Purchase Model","Clicks Per Minute","Campaign Performance Metric"],c:"Cost Per Mille"},
  {q:"Which marketing type relies on word of mouth?",a:["Viral marketing","Print marketing","Cold calling","Outdoor advertising"],c:"Viral marketing"},
  {q:"What is market segmentation?",a:["Dividing customers by traits","Combining all markets","Ignoring demographics","Selling one product to all"],c:"Dividing customers by traits"},
  {q:"What does CTA mean?",a:["Call to Action","Customer Tracking Alert","Click to Advertise","Campaign Target Area"],c:"Call to Action"},
  {q:"What is brand equity?",a:["Value from brand perception","Company stock value","Logo design cost","Marketing budget"],c:"Value from brand perception"},
  {q:"Which marketing method is oldest?",a:["Print ads","Email marketing","Social media ads","SEO"],c:"Print ads"},
  {q:"What is a key benefit of digital marketing?",a:["Real-time analytics","Low creativity","Slow feedback","Local reach only"],c:"Real-time analytics"},
  {q:"What’s A/B testing?",a:["Testing two versions","Testing sound quality","Two-person survey","Budget review"],c:"Testing two versions"},
  {q:"What does CRM stand for?",a:["Customer Relationship Management","Content Research Marketing","Creative Resource Model","Consumer Reach Metric"],c:"Customer Relationship Management"},
  {q:"What’s a KPI?",a:["Key Performance Indicator","Knowledge Point Index","Known Product Insight","Key Price Item"],c:"Key Performance Indicator"},
  {q:"Who said 'The consumer isn’t a moron, she’s your wife'?",a:["David Ogilvy","Edward Bernays","Philip Kotler","Leo Burnett"],c:"David Ogilvy"},
  {q:"What is storytelling used for in marketing?",a:["Emotional connection","Price display","Hard selling","Product labeling"],c:"Emotional connection"},
  {q:"What is digital marketing?",a:["Promoting products or services using online channels","Selling goods in physical stores","Advertising on TV and radio only","Word-of-mouth marketing"],c:"Promoting products or services using online channels"},
  {q:"Which of the following is NOT a form of digital marketing?",a:["Billboard advertising","Email marketing","Social media marketing","Search engine marketing"],c:"Billboard advertising"},
  {q:"What does SEO stand for?",a:["Search Engine Optimization","Social Engagement Operations","Sales Enhancement Online","Systematic Engagement Output"],c:"Search Engine Optimization"},
  {q:"The goal of SEO is to:",a:["Improve a website’s ranking on search engines","Create paid ads","Design logos","Send promotional emails"],c:"Improve a website’s ranking on search engines"},
  {q:"What is PPC in digital marketing?",a:["Pay Per Click","Post Per Comment","Pay Per Conversion","Public Promotion Campaign"],c:"Pay Per Click"},
  {q:"Which platform is best known for PPC advertising?",a:["Google Ads","Instagram","LinkedIn","Snapchat"],c:"Google Ads"},
  {q:"What is content marketing?",a:["Creating valuable content to attract and engage customers","Posting random updates online","Buying followers on social media","Using paid ads only"],c:"Creating valuable content to attract and engage customers"},
  {q:"What is the main purpose of social media marketing?",a:["Building brand awareness and engagement","Reducing website traffic","Ignoring customer feedback","Selling only physical products"],c:"Building brand awareness and engagement"},
  {q:"What does CTR stand for?",a:["Click Through Rate","Customer Transaction Ratio","Conversion Tracking Report","Cost To Revenue"],c:"Click Through Rate"},
  {q:"Which metric measures how many visitors leave a website after viewing only one page?",a:["Bounce rate","Conversion rate","Click rate","Engagement rate"],c:"Bounce rate"},
  {q:"What does KPI stand for in marketing?",a:["Key Performance Indicator","Keyword Performance Insight","Knowledge Point Index","Key Promotion Idea"],c:"Key Performance Indicator"},
  {q:"Which of these is an example of inbound marketing?",a:["Publishing blog posts","Cold calling","Door-to-door sales","TV commercials"],c:"Publishing blog posts"},
  {q:"What is email marketing mainly used for?",a:["Building relationships with customers","Replacing social media","Designing websites","Tracking ads"],c:"Building relationships with customers"},
  {q:"What is a landing page?",a:["A page designed to capture leads or drive a specific action","The homepage of a website","A contact page","An error page"],c:"A page designed to capture leads or drive a specific action"},
  {q:"What is remarketing?",a:["Targeting people who previously visited your website","Marketing for new products only","Posting ads offline","Optimizing search engines"],c:"Targeting people who previously visited your website"},
  {q:"What is influencer marketing?",a:["Partnering with people who have large online followings","Hiring celebrities for TV ads","Paying search engines for visibility","Creating anonymous ads"],c:"Partnering with people who have large online followings"},
  {q:"Which platform is most visual and image-focused?",a:["Instagram","LinkedIn","Twitter","Reddit"],c:"Instagram"},
  {q:"What does ROI stand for?",a:["Return On Investment","Rate Of Interest","Reach On Internet","Revenue On Impressions"],c:"Return On Investment"},
  {q:"What is affiliate marketing?",a:["Earning commissions by promoting other companies’ products","Buying ads on social media","Selling your own products only","Creating your own social platform"],c:"Earning commissions by promoting other companies’ products"},
  {q:"What is a conversion in digital marketing?",a:["When a user completes a desired action","When a website loads","When a user leaves a site","When an ad is clicked but ignored"],c:"When a user completes a desired action"},
  {q:"What is Google Analytics used for?",a:["Tracking and analyzing website traffic","Creating email campaigns","Designing graphics","Posting social media updates"],c:"Tracking and analyzing website traffic"},
  {q:"What does SEM stand for?",a:["Search Engine Marketing","Social Engagement Metrics","Sales Enablement Management","Systematic Email Marketing"],c:"Search Engine Marketing"},
  {q:"What is the purpose of A/B testing?",a:["To compare two versions of a webpage or ad","To test ad placement on billboards","To analyze employee performance","To run surveys only"],c:"To compare two versions of a webpage or ad"},
  {q:"What does ‘organic traffic’ mean?",a:["Visitors who find your site naturally via search engines","Paid ad visitors","Referral traffic from ads","Traffic from email campaigns"],c:"Visitors who find your site naturally via search engines"},
  {q:"What is a marketing funnel?",a:["A model showing the steps customers take before purchase","A physical sales device","A social media campaign","An SEO strategy"],c:"A model showing the steps customers take before purchase"},
  {q:"Which of these improves SEO ranking?",a:["High-quality backlinks","Duplicate content","Keyword stuffing","Irrelevant links"],c:"High-quality backlinks"},
  {q:"What does CTA stand for?",a:["Call To Action","Customer Target Analysis","Click To Advertise","Cost Tracking Algorithm"],c:"Call To Action"},
  {q:"What is native advertising?",a:["Ads that match the style and format of the platform","Unrelated pop-up ads","Banner ads only","Hidden paid promotions"],c:"Ads that match the style and format of the platform"},
  {q:"Which tool helps schedule and manage social media posts?",a:["Hootsuite","Excel","Google Docs","WordPress"],c:"Hootsuite"},
  {q:"What is the main advantage of digital marketing over traditional marketing?",a:["Precise targeting and measurable results","Higher TV exposure","More physical stores","No need for a website"],c:"Precise targeting and measurable results"}
];