let seoQuestions = [
  {q:"What does SEO stand for?",a:["Search Engine Optimization","Social Engagement Order","System Enhancement Output","Site Engine Operation"],c:"Search Engine Optimization"},
  {q:"Which search engine is the most popular?",a:["Google","Bing","Yahoo","DuckDuckGo"],c:"Google"},
  {q:"What is a keyword?",a:["A search term users type","A company slogan","An HTML tag","An image caption"],c:"A search term users type"},
  {q:"What is on-page SEO?",a:["Optimizing content on the site","Linking to other sites","Running paid ads","Tracking conversions"],c:"Optimizing content on the site"},
  {q:"What is off-page SEO?",a:["Building backlinks","Improving site speed","Using alt text","Writing meta descriptions"],c:"Building backlinks"},
  {q:"What does SERP stand for?",a:["Search Engine Results Page","Site Engagement Rate Performance","Search Engine Ranking Performance","Systematic Engine Result Page"],c:"Search Engine Results Page"},
  {q:"Which tag defines the title of a webpage?",a:["<title>","<meta>","<h1>","<header>"],c:"<title>"},
  {q:"What is a backlink?",a:["A link from another website to yours","A link to your homepage","An internal link","A social media mention"],c:"A link from another website to yours"},
  {q:"What is the purpose of meta descriptions?",a:["Summarize page content in search results","Display keywords on screen","Speed up loading time","Change site layout"],c:"Summarize page content in search results"},
  {q:"What tool is commonly used for keyword research?",a:["Google Keyword Planner","Google Calendar","Canva","Dropbox"],c:"Google Keyword Planner"},
  {q:"What is domain authority?",a:["A score that predicts ranking ability","Website ownership verification","Server uptime measure","A hosting plan type"],c:"A score that predicts ranking ability"},
  {q:"Which file helps search engines index pages?",a:["sitemap.xml","robots.txt","index.html","about.html"],c:"sitemap.xml"},
  {q:"Which file tells crawlers what not to index?",a:["robots.txt","sitemap.xml","index.html","meta file"],c:"robots.txt"},
  {q:"What is mobile-first indexing?",a:["Google prioritizes mobile content","Websites only for phones","Desktop version indexing first","App-only ranking system"],c:"Google prioritizes mobile content"},
  {q:"What’s the ideal length for a meta title?",a:["50–60 characters","20–30 characters","90–100 characters","120 characters"],c:"50–60 characters"},
  {q:"What are long-tail keywords?",a:["Specific multi-word phrases","One-word general terms","Trending hashtags","Random words"],c:"Specific multi-word phrases"},
  {q:"What is black hat SEO?",a:["Using unethical SEO tactics","Optimizing legally","Following Google guidelines","Social media SEO"],c:"Using unethical SEO tactics"},
  {q:"What is alt text used for?",a:["Describing images","Changing font color","Embedding links","Adding keywords to headings"],c:"Describing images"},
  {q:"Which metric measures how long visitors stay?",a:["Dwell time","Bounce rate","CTR","Conversion rate"],c:"Dwell time"},
  {q:"What does CTR mean?",a:["Click-Through Rate","Content Tracking Ratio","Customer Traffic Rate","Conversion Tracking Report"],c:"Click-Through Rate"},
  {q:"What is local SEO?",a:["Optimizing for nearby searches","Advertising on radio","Running global ads","Designing social posts"],c:"Optimizing for nearby searches"},
  {q:"What is schema markup?",a:["Code that helps search engines understand content","An HTML color scheme","A link-building technique","An analytics tool"],c:"Code that helps search engines understand content"},
  {q:"What is page speed important for?",a:["User experience and rankings","Image design","Social media engagement","Video uploads"],c:"User experience and rankings"},
  {q:"What is the core web vitals metric NOT about?",a:["Social media likes","Page speed","Interactivity","Visual stability"],c:"Social media likes"},
  {q:"Which platform owns Google Search Console?",a:["Google","Microsoft","Meta","Yahoo"],c:"Google"},
  {q:"What is the best practice for URLs?",a:["Short, clear, and keyword-rich","Random and long","With many numbers","With no words"],c:"Short, clear, and keyword-rich"},
  {q:"What does 'nofollow' mean?",a:["A link that doesn’t pass SEO value","A broken link","A paid link","An internal link"],c:"A link that doesn’t pass SEO value"},
  {q:"What’s E-E-A-T in SEO?",a:["Experience, Expertise, Authoritativeness, Trust","Engagement, Entertainment, Ads, Traffic","Evaluation, Education, Ads, Time","External, Emotional, Awareness, Tactics"],c:"Experience, Expertise, Authoritativeness, Trust"},
  {q:"What’s Google’s latest AI ranking system called (as of 2025)?",a:["Search Generative Experience (SGE)","RankBrain","BERT","Hummingbird"],c:"Search Generative Experience (SGE)"},
  {q:"What is canonicalization used for?",a:["Preventing duplicate content issues","Increasing backlinks","Improving images","Adding animations"],c:"Preventing duplicate content issues"}
];